package com.sap.adt.abapcleaner.rulehelpers;

public class CommentIdentification {
	final int reasonsProCode;
	final int reasonsProText;
	final int reasonsProEnglish;
	final int reasonsProGerman;
	public final int indent;
	public final String[] words;
	final String reasons;
	public final boolean isAutoGenerated;

	public final boolean canDecide() { return (reasonsProCode > 0 || reasonsProText > 0); }

	final double getCodeProbability() {
		return (reasonsProCode == 0 && reasonsProText == 0) ? Double.NaN : reasonsProCode / (double) (reasonsProCode + reasonsProText);
	}

	public final int getCodeProbabilityPercent() { return (int) (getCodeProbability() * 100.0); }

	public final boolean isCode() { return (getCodeProbability() > 0.5); }

	public final boolean isTextual() { return !isCode(); }

	public final boolean isEnglish() { return isTextual() && (reasonsProGerman <= reasonsProEnglish); }
	
	public final boolean isGerman() { return isTextual() && (reasonsProGerman > reasonsProEnglish); }
	
	public final String getReasonsWithSep(String sep) {
		return (reasons == null) ? "" : reasons.replace(System.lineSeparator(), sep);
	}

	CommentIdentification(int proCode, int proText, int proEnglish, int proGerman, int indent, StringBuilder reasons, String[] words, boolean isAutoGenerated) {
		reasonsProCode = proCode;
		reasonsProText = proText;
		reasonsProEnglish = proEnglish;
		reasonsProGerman = proGerman;
		this.indent = indent;
		this.reasons = (reasons == null) ? null : reasons.toString();
		this.words = words;
		this.isAutoGenerated = isAutoGenerated;
	}
}