package com.sap.adt.abapcleaner.rulehelpers;

public class CommentIdentification {
	final int reasonsProAbap;
	final int reasonsProText;
	final int reasonsProEnglish;
	final int reasonsProGerman;
	public final int indent;
	public final String[] words;
	final String reasons;
	public final boolean isAutoGenerated;

	public final boolean canDecide() { return (reasonsProAbap > 0 || reasonsProText > 0); }

	final double getAbapProbability() {
		return (reasonsProAbap == 0 && reasonsProText == 0) ? Double.NaN : reasonsProAbap / (double) (reasonsProAbap + reasonsProText);
	}

	public final int getAbapProbabilityPercent() { return (int) (getAbapProbability() * 100.0); }

	public final boolean isAbapCode() { return (getAbapProbability() > 0.5); }

	public final boolean isTextual() { return !isAbapCode(); }

	public final boolean isEnglish() { return isTextual() && (reasonsProGerman <= reasonsProEnglish); }
	
	public final boolean isGerman() { return isTextual() && (reasonsProGerman > reasonsProEnglish); }
	
	public final String getReasonsWithSep(String sep) {
		return (reasons == null) ? "" : reasons.replace(System.lineSeparator(), sep);
	}

	CommentIdentification(int proAbap, int proText, int proEnglish, int proGerman, int indent, StringBuilder reasons, String[] words, boolean isAutoGenerated) {
		reasonsProAbap = proAbap;
		reasonsProText = proText;
		reasonsProEnglish = proEnglish;
		reasonsProGerman = proGerman;
		this.indent = indent;
		this.reasons = (reasons == null) ? null : reasons.toString();
		this.words = words;
		this.isAutoGenerated = isAutoGenerated;
	}
}